---
- hosts : all
  gather_facts: false
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 20
        sleep: 10
        timeout: 300

- hosts : all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:

  - name: Install Docker
    yum:
      name: docker
      state: latest

  - name: Start Docker
    service:
      name: docker
      state: started
      enabled: yes

  - name: Modify User
    user:
      name: ec2-user
      groups: docker
      append: yes

  - name: Install docker-compose
    pip:
      name: docker-compose>1.7.0,<2.0.0
      executable: pip3
    
  - name: clone docker-compose
    copy:
       src: ../docker/docker-compose.yml
       dest: /home/ec2-user/
       owner: ec2-user
       group: ec2-user
       mode: "0644"
       directory_mode: "0755"
  - name: ejecute docker-compose
    community.docker.docker_compose:
       project_src: /home/ec2-user/
       pull: true
    vars:
       ansible_python_interpreter: /usr/bin/python3
